import { markdownToHTML } from "comrak"
import xxhash from "xxhash-wasm"
import { createHighlighter } from "shiki"

import { 
  normalize
  collapse 
  toLowerCase
  dashed 
} from "@dashkite/joy/text"

import { pipe } from "@dashkite/joy/function"

Key =
  make: pipe [ normalize, collapse, toLowerCase, dashed ]
  wrap: ( f ) ->
    ({ context..., content }) ->
      id = Key.make content
      f { context..., content, id }

cache = {}
highlighter = undefined
markdown = ->

  highlighter ?= await createHighlighter
    themes: [
      "github-light"
      "github-dark"
      "github-light-high-contrast"
      "github-dark-high-contrast" 
    ]
    langs: [ "javascript", "coffeescript", "css", "html", "yaml" ]

  options =
    extension:
      autolink: true
      # descriptionLists: true
      footnotes: true
      # frontMatterDelimiter: "---"
      # headerIDs: "heading-"
      table: true
      tagfilter: true
      tasklist: true
      alerts: true
      mathDollars: true
      mathCode: true
      strikethrough: true
      strikethrough: true
      superscript: true
      shortcodes: true
      # highlight: true
    parse:
      smart: true
      # TODO add broken link handler
      # brokenLinkCallback: TBD
    render:
      githubPreLang: true
      unsafe: true
      figureWithCaption: true
    plugins:
      render:
        headingAdapter:
          enter: Key.wrap ({ level, id }) ->
            "<h#{ level } id='#{ id }'>"
          exit: Key.wrap ({ level, id }) ->
            "<a aria-hidden='true' tabindex='-1' href='##{ id }'>
                <i class='ri-link-m' aria-hidden></i>
                <span class='hidden'>Permalink</span>
              </a>
            </h#{ level }>"
        codefenceSyntaxHighlighter:
          highlight: ( code, language ) ->
            highlighter.codeToHtml code, 
              lang: language
              themes:
                light: "github-light-high-contrast"
                dark: "github-dark-high-contrast"
              defaultColor: "light-dark()"
          # these are generated by shiki
          pre: -> ""
          code: -> ""

  hash = ( await xxhash()).h32
  
  ({ input }) ->
    # markdownToHTML input, options
    cache[ hash input ] ?= do ->
      # 1. Comrak parse & render in Rust
      html = markdownToHTML input, options
      
      # 2. Match your admonition format (:::info ... :::)
      # Since Comrak doesn't natively support remark-directive yet,
      # we use a fast regex for this specific transformation.
      html = html.replace /:::(\w+)\n([\s\S]*?)\n:::/g, (match, type, content) ->
        "<div class=\"admonition admonition-#{type}\">#{content}</div>"
        
      # 3. Autolink Headings Approximation
      # Comrak's headerIDs provides the `id`, but we'll add the 
      # link icons via regex to match your original configuration.
      html = html.replace /<(h[1-6]) id="([^"]+)">([^<]+)<\/\1>/g, (match, tag, id, content) ->
        """
        <#{tag} id="#{id}">#{content}<a aria-hidden="true" tabindex="-1" href="##{id}"><i class="ri-link-m" aria-hidden="true"></i><span class="hidden">Permalink</span></a></#{tag}>
        """

      html

export default markdown
export { markdown }
